name: Matrix
on: push

jobs:
  node-version:
    runs-on: ubuntu-latest
    steps:
      - name: Install before log node version
        run: node -v
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Install after log node version
          run: node -v